In [2]:
import tensorflow as tf

In [27]:
!pip show tensorflow

Name: tensorflow
Version: 2.2.0
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: /home/siddhesh/anaconda3/lib/python3.7/site-packages
Requires: wheel, termcolor, wrapt, h5py, google-pasta, gast, protobuf, scipy, grpcio, astunparse, keras-preprocessing, numpy, opt-einsum, tensorflow-estimator, absl-py, six, tensorboard
Required-by: 


In [3]:
tf.Graph()

In [4]:
tf2x=tf.compat.v1

In [5]:
mygraph=tf.Graph()
with mygraph.as_default():
    a=tf.constant(3)
    b=tf.constant(4)
session=tf2x.Session(graph=mygraph)
print(session.run(a))
session.close()
    

3


In [6]:
tf2x.InteractiveSession()

In [7]:
with tf2x.Session() as sess:
    print(sess.run(tf.constant(9)+tf.constant(10)))

19


In [8]:
c=tf.add(tf.constant(9),tf.constant(10),name=None)

In [9]:
## This in an attribute of the object we get after addition
c.numpy()

19

In [10]:
a=tf.ones((3,3))-tf.zeros((3,3))

In [11]:
a

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [12]:
c=tf.subtract(tf.constant(9),tf.constant(10),name=None)

In [13]:
c.numpy()

-1

In [14]:
a=tf.constant((3,4,5))

In [15]:
c=a.numpy()

In [16]:
k=tf.eye(5)

In [17]:
k.numpy()

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)

In [18]:
a=tf.constant((8,9,10,11))

In [21]:
z=tf2x.diag(a)

In [22]:
z.numpy()

array([[ 8,  0,  0,  0],
       [ 0,  9,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 11]], dtype=int32)

In [24]:
# Tensors can also be created using the 'tf.random_normal' - this is an attribute
# Here you can specify the mean and standard deviation of then random values
tf2x.random_normal((3,3), mean=1, stddev=2).numpy()

array([[ 2.5115938 ,  4.9480276 ,  3.662058  ],
       [-1.3401887 ,  1.6744001 ,  0.30433625],
       [ 2.8882685 ,  0.97056377, -0.39436424]], dtype=float32)

In [25]:
# Another attribute is the 'tf.truncated_normal()' - this is used when working with large samples
# Due to Numerical Stability, it is advisable to use this attribute

tf2x.truncated_normal((50,50), mean=0.1, stddev=3).numpy()

array([[ 3.6759849 ,  0.25358906, -1.8186284 , ...,  0.2425195 ,
        -5.303369  ,  3.9972947 ],
       [-0.29976138,  1.5507121 ,  3.1275306 , ..., -1.3829626 ,
         2.6844141 ,  1.9698876 ],
       [-0.971773  , -2.9131029 ,  1.5003103 , ..., -0.9533676 ,
        -1.6339737 , -4.842213  ],
       ...,
       [-0.39260137, -2.3750412 , -1.3857793 , ...,  1.0312858 ,
        -0.8226875 ,  1.3403736 ],
       [ 5.354195  ,  0.92338955, -0.8585895 , ..., -1.3082509 ,
        -0.14059642, -2.66368   ],
       [ 0.6379534 , -3.7928903 , -4.558435  , ...,  3.991284  ,
        -0.33848622,  0.11656146]], dtype=float32)

In [26]:
# The 'tf.random_uniform' also behaves like the random_normal, except that it is specified a range
# It's values are sampled from a Uniform Distribution - hence the name

tf2x.random_uniform((3,3), minval=0, maxval=1).numpy()

array([[0.7705643 , 0.49210083, 0.3506496 ],
       [0.10303676, 0.17441571, 0.890373  ],
       [0.68989754, 0.7427666 , 0.48117113]], dtype=float32)

In [28]:
a = tf.fill((3,2),2).numpy()
a

array([[2, 2],
       [2, 2],
       [2, 2]], dtype=int32)

In [29]:
b = tf.range(0,2,1).numpy()
b

array([0, 1], dtype=int32)

In [30]:
# Note that the two tensors are of the same type, else TensorFlow will raise a type error
# The vector 'b' was added along each row of the matrix

a + b

array([[2, 3],
       [2, 3],
       [2, 3]], dtype=int32)

In [31]:
# Broadcasting can also happen along the columns, take the examples below for instance

c = tf.fill((3,1),3).numpy()
c

array([[3],
       [3],
       [3]], dtype=int32)

## Defining the matrices

In [34]:
graph5 = tf2x.Graph()
with graph5.as_default():
    a = tf.constant([5])
    b = tf.constant([2])
    c = tf.add(a,b)
    d = tf.subtract(a,b)

with tf2x.Session(graph = graph5) as sess:
    result = sess.run(c)
    print ('c =: %s' % result)
    result = sess.run(d)
    print ('d =: %s' % result)

c =: [7]
d =: [3]


In [35]:
graph3 = tf2x.Graph()
with graph3.as_default():
    Matrix_one = tf.constant([[1,2,3],[2,3,4],[3,4,5]])
    Matrix_two = tf.constant([[2,2,2],[2,2,2],[2,2,2]])

    add_1_operation = tf.add(Matrix_one, Matrix_two)
    add_2_operation = Matrix_one + Matrix_two

with tf2x.Session(graph =graph3) as sess:
    result = sess.run(add_1_operation)
    print ("Defined using tensorflow function :")
    print(result)
    result = sess.run(add_2_operation)
    print ("Defined using normal expressions :")
    print(result)

Defined using tensorflow function :
[[3 4 5]
 [4 5 6]
 [5 6 7]]
Defined using normal expressions :
[[3 4 5]
 [4 5 6]
 [5 6 7]]


In [37]:
graph2 = tf2x.Graph()
with graph2.as_default():
    Scalar = tf.constant(2)
    Vector = tf.constant([5,6,2])
    Matrix = tf.constant([[1,2,3],[2,3,4],[3,4,5]])
    Tensor = tf.constant( [ [[1,2,3],[2,3,4],[3,4,5]] , [[4,5,6],[5,6,7],[6,7,8]] , [[7,8,9],[8,9,10],[9,10,11]] ] )
with tf2x.Session(graph = graph2) as sess:
    result = sess.run(Scalar)
    print ("Scalar (1 entry):\n %s \n" % result)
    result = sess.run(Vector)
    print ("Vector (3 entries) :\n %s \n" % result)
    result = sess.run(Matrix)
    print ("Matrix (3x3 entries):\n %s \n" % result)
    result = sess.run(Tensor)
    print ("Tensor (3x3x3 entries) :\n %s \n" % result)

Scalar (1 entry):
 2 

Vector (3 entries) :
 [5 6 2] 

Matrix (3x3 entries):
 [[1 2 3]
 [2 3 4]
 [3 4 5]] 

Tensor (3x3x3 entries) :
 [[[ 1  2  3]
  [ 2  3  4]
  [ 3  4  5]]

 [[ 4  5  6]
  [ 5  6  7]
  [ 6  7  8]]

 [[ 7  8  9]
  [ 8  9 10]
  [ 9 10 11]]] 



## Some Operations

In [57]:
c=0.4
sigma=tf.constant([5.3,6,2])
R=tf.constant([0.8,0.7,0.7])
C=tf.constant([0.3,0.4,0.5])
W=tf.constant([300.0,500,600])
Matrix = tf.constant([[1,2,3],[2,3,4],[3,4,5]])

In [58]:
## Element wise multiplication
tf.math.multiply(R, C, name=None)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.24000001, 0.28      , 0.35      ], dtype=float32)>

In [59]:
# Defining the terms
K=R-C

z=tf.math.multiply(K, sigma, name=None)
## This is the actual f from the document
f=tf.math.multiply(z, W, name=None)
