<div class="alert alert-block alert-success" style="margin-top: 20px">
 <h1>Getting Started with TensorFlow</h1>
</div>

In [1]:
# Created by: ADMINIXTRATOR             Date: 9th January, 2020
# Twitter: Adminixtrator                Email: minixtrator@gmail.com
# 
# Python version: 3.7.4 amd64 (64-bit)    TensorFlow: 2.0.0


import tensorflow as tf

In [2]:
# To use TensorFlow 2x, you need to add '.compat.v1' before the attribute
# Although you can define your TF 2x to behave like 1x

tf.compat.v1.InteractiveSession()

# Experimenting with tensorflow interactively

In [3]:
# Another way to make our lives easier is to declare another variable to hold the module 'tf.compat.v1'

tf2x = tf.compat.v1

In [4]:
tf2x.InteractiveSession()

# Voila.. 
# Now all other attributes will be addressed with 'tf2x.<Session>'

c:\users\funminiyi sadiq\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\client\session.py:1750: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [5]:
# The easiest conventions in creating a Tensor are 'tf.zeros' and 'tf.ones'
# To show the created Tensor you call 'tf.Tensor.eval()' - in this case, it will be 'tf.Tensor.numpy()' since we are in an 
# interactive session
# The 'tf.eval' is the same as your 'np.ndarray' - Numpy
# TensorFlow was built to be compatible with Numpy conventions

tf.zeros(2)

<tf.Tensor: id=3, shape=(2,), dtype=float32, numpy=array([0., 0.], dtype=float32)>

In [6]:
#   tf.zeros((3,3)).eval()  -   The eval function does not work because we are in an InteractiveSession

tf.zeros((3,3)).numpy()

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [7]:
tf.ones((2,2,2)).numpy()

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]], dtype=float32)

In [8]:
# Another method is the 'tf.fill()' - create tensors of quantities beside 1/0
# The 'tf.constant()' is used to create Tensors that will not change throughout the program execution

tf.fill((3,3), value=3).numpy()

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [9]:
tf.constant(12).numpy()

12

In [10]:
# Tensors can also be created using the 'tf.random_normal' - this is an attribute
# Here you can specify the mean and standard deviation of then random values

tf2x.random_normal((3,3), mean=1, stddev=2).numpy()

array([[-2.2285936 ,  1.4933051 ,  0.03604329],
       [ 1.634942  , -0.55107546,  0.3679331 ],
       [ 0.5500853 ,  2.0355678 , -0.5707518 ]], dtype=float32)

In [11]:
# Another attribute is the 'tf.truncated_normal()' - this is used when working with large samples
# Due to Numerical Stability, it is advisable to use this attribute

tf2x.truncated_normal((50,50), mean=0.1, stddev=3).numpy()

array([[ 2.1833906 ,  0.16011885,  1.167581  , ...,  1.3656489 ,
         3.413081  , -2.3120842 ],
       [-0.6460326 ,  1.0959543 ,  1.7580105 , ..., -1.2340318 ,
         2.010972  ,  0.39672688],
       [-0.858003  , -3.8768098 , -0.36111295, ..., -2.657211  ,
         1.8106611 , -3.0877113 ],
       ...,
       [-3.3364859 ,  3.142448  , -4.0399776 , ..., -3.65737   ,
         3.7172432 , -2.1294777 ],
       [ 4.4432693 , -3.0632572 ,  2.4816728 , ...,  4.394312  ,
        -2.3020859 , -3.6823502 ],
       [-0.42149058, -1.0195161 , -4.276531  , ..., -0.97110236,
        -2.8536296 , -0.97242105]], dtype=float32)

In [12]:
# The 'tf.random_uniform' also behaves like the random_normal, except that it is specified a range
# It's values are sampled from a Uniform Distribution - hence the name

tf2x.random_uniform((3,3), minval=0, maxval=1).numpy()

array([[0.91220176, 0.18596375, 0.85654044],
       [0.54235315, 0.4872867 , 0.6222974 ],
       [0.5697758 , 0.23914456, 0.82107747]], dtype=float32)

In [ ]:
#                        NEXT == Tensor Addition and Scaling